model: CombSub
prediction_phase: False
prediction_f0: False
sampling_rate: 44100
block_size: 512
win_length: 2048
use_mean_filter: True
n_mag_harmonic: 512
n_mag_noise: 256
n_frames: 1000
lr: 0.1
num_epochs: 1000
f0_min: 40
f0_max: 700
fft_min: 256
fft_max: 2048
n_scale: 4
lambda_uv: 1
device: cuda