data:
  f0_extractor: 'parselmouth' # 'parselmouth' (singing) or 'dio' (speech) or 'harvest' (speech)
  f0_min: 65 # about C2
  f0_max: 800 # about G5
  sampling_rate: 44100
  n_fft: 2048
  win_size: 2048
  hop_size: 512 # Equal to hop_length
  n_mels: 128
  mel_fmin: 40 
  mel_fmax: 16000 # <= sampling_rate / 2 
  max_nhar: 128 # must be equal to model.n_sin_hars
  # directories: ['audio', 'haudio', 'mel', 'f0', 'uv', 'ampl', 'phase']
  mel_clamp: 0.000001 # clamp the output of the model to avoid numerical instability


  uv_noise_k : 512
loss:
  fft_min: 256
  fft_max: 2048
  n_scale: 4 # rss kernel numbers
  uv_tolerance: 0.05 # set it to a large value or try other f0 extractors if val_loss_uv is much higher than train_loss_uv
  detach_uv_step: 200
device: cuda
train:

  epochs: 100
  lr: 0.0005
  weight_decay: 0